# Generated by Django 3.2.12 on 2024-04-05 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Office', '0005_auto_20240325_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_left',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=256, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('batch', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
