# Generated by Django 3.2.12 on 2024-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0006_auto_20240405_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_pay_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_pay_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
