# Generated by Django 3.2.12 on 2024-04-21 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Office', '0007_auto_20240405_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('branch', models.CharField(choices=[('computer engineering', 'computer engineering'), ('mechanical engineering', 'mechanical engineering'), ('electrical engineering', 'electrical engineering'), ('electronics and communication engineering', 'electronics and communication engineering')], max_length=60)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='tbl_leave_type',
            fields=[
                ('leave_id', models.IntegerField(primary_key=True, serialize=False)),
                ('leave_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tbl_leave_type',
                'verbose_name_plural': 'tbl_leave_types',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leaverecord',
            name='employee',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='LeaveRecord',
        ),
    ]
