# Generated by Django 3.2.12 on 2024-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0010_tbl_leave_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_leave_apply',
            name='leave_id',
        ),
        migrations.AddField(
            model_name='tbl_leave_apply',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Earned Leave', 'Earned Leave'), ('Sick leave', 'Sick leave')], max_length=100, null=True),
        ),
    ]
