# Generated by Django 3.2.12 on 2024-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0013_alter_tbl_leave_apply_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_leave_apply',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
